// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFnmXbZCGTKarOKecfWiGUDM0C7Rfxa2Q',
    appId: '1:365535867982:android:eadce113e30c6b9af33f1f',
    messagingSenderId: '365535867982',
    projectId: 'digiatt-corp',
    storageBucket: 'digiatt-corp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSaXIdo77NXbHFp1a-xU2oLuMohd1S0kw',
    appId: '1:365535867982:ios:e32df7db2b4aa58ef33f1f',
    messagingSenderId: '365535867982',
    projectId: 'digiatt-corp',
    storageBucket: 'digiatt-corp.appspot.com',
    androidClientId: '365535867982-668vafvf12s9u500r070uugjsc5vdupr.apps.googleusercontent.com',
    iosClientId: '365535867982-soco9af6eahoht5ea0i4plpke2kum9tn.apps.googleusercontent.com',
    iosBundleId: 'com.example.digiatt',
  );
}
